db:
  host: "mongodb"
  port: "27017"
  collection: "items"
  db: "db"

logic:
  delay_time: "2s"

kafka:
  brokers:
    - "kafka:9092"
  yandex_consumer_group: "yandex-group"
  ebay_consumer_group: "ebay-group"
  yandex_topic: "yandex_url-topic"
  ebay_topic: "ebay-url-topic"
